### ISSUE TITLE
Why is the adapter in the `public` directory?

### ISSUE THREAD

**Issue by dandv** [webix-hub/webix-meteor-example#1]
Usually, client code would go in the `client` directory, which Meteor loads automatically. Is it because of some load order issue? I tried to package Webix in a Meteor package, but with the adapter file loaded on the client by default, I get odd errors:

```
webix_debug.js:18892 Uncaught TypeError: Cannot read property 'datatable' of undefined
```

**Comment by mkozhukh** [comment]
Yep, it caused by the initialization order

Logic of adapter need to be executed after loading webix.js on the page ( it extends webix,proxy collection ) and as far as I can see files from "client" will always be loaded before external references. 

It possible to workaround it by wrapping the code in meteor.ready and webix.ready but it complicates sample even more than usage of "public" folder.

**Comment by dandv** [comment]
The Meteor way to control file load order is to put files in packages, so I've created a [Webix package for Meteor](https://github.com/webix-hub/tracker/pull/210).
